import Hexagon from '../Components/Hexagon.jsx'
import HexBackground from '../Components/HexBackground.jsx'
import { motion, useMotionValue, AnimatePresence, animate } from 'framer-motion'
import { useState, useEffect, useRef, useCallback, useMemo, Fragment } from 'react'
import { playSFX } from '../utils/audio'

// This is the orbiting orb animation. Pretty easy, goes from left, to top of hex, also defined by Hexcolor from Hexdata due to parameter.
function BorderChase({ left, top, color }) {
    return (
        <motion.div
            style={{ position: 'absolute', left, top, width: '10px', height: '10px',
                     borderRadius: '50%', backgroundColor: color, zIndex: 6,
                     pointerEvents: 'none', boxShadow: `0 0 8px 4px ${color}99` }}
            initial={{ opacity: 0 }}
            animate={{ x: [128, 256, 256, 128, -5, -5, 128], y: [-5, 71, 225, 301, 225, 71, -5], opacity: 1 }}
            transition={{
                x: { duration: 4, repeat: Infinity, ease: 'linear', times: [0, 1/6, 2/6, 3/6, 4/6, 5/6, 1] },
                y: { duration: 4, repeat: Infinity, ease: 'linear', times: [0, 1/6, 2/6, 3/6, 4/6, 5/6, 1] },
                opacity: { duration: 0.5, delay: 2.5 }
            }}
        />
    )
}

// Rainbow palette for the 6 hexagon fill. Yes, the rainbow easter egg is not generated by math logic. such a shame ik. 
const RB_COLORS  = ['#FF3333', '#FF8800', '#FFE600', '#33CC33', '#2288FF', '#AA00FF']
const RB_BORDERS = ['#CC0000', '#CC6600', '#CCAA00', '#228822', '#0055CC', '#7700CC']
const RB_LIGHT   = ['#FFB3B3', '#FFDDAA', '#FFFFC0', '#AAFFAA', '#AACCFF', '#DDAAFF']

// The positioning of each hex per canvas from the left. Formula: (left + 133, top + 153) <-- IT SHOULD BE 132.5 BUT THIS DAMN AI DOESN'T GENERALIZE IT, EVER. ALWAYS CHECK CLAUDE
// lightColor background tint when this hex is selected
const hex = (label = "Polygon Button", para1 = "Placeholder text one.", para2 = "Placeholder text two.", color = "#D0DCD3", textColor = "#000000", lightColor = "#EEFBEF", pos = { x: 0, y: 0 }) =>
    ({ label, para1, para2, color, textColor, lightColor, pos })
//PREPARE FOR THE HEXDATA WALL OF TEEEEEEEEEEEEXT
//I got lazy with the placeholders in the transform hexes, didn't even need to place them, but it's good for consistency.. 
const hexData = {
    hex2:  hex("Job Experience",                "RAHHHHHHHHHH", "Placeholder text two.", "#F29E4C", "#FFFFFF", "#FDCA64", { x: 265.5, y: 153 }),
    hex3:  hex("Coding Experience",             "RAHHHHHHHHHH", "RAHHHHHHHHHH", "#000000", "#FFFFFF", "#111111", { x: 530.5, y: 153 }),
    hex4:  hex("Education",                     "RAHHHHHHHHHH", "Placeholder text two.", "#1D4ED8", "#FFFFFF", "#DBEAFE", { x: 133,   y: 382 }),
    hex5:  hex("Gabriel Lago Personal Overview", "Welcome to my website! Please touch any hexagons to expand on any topic, and then touch that topic to see what I know about it!", "This took a long time to make, but the mathematical formulas used were fun to learn. I hope you enjoy seeing this website as much as I do.", "#FFFFFF", "#000000", "#EEFBEF", { x: 398,   y: 382 }),
    hex6:  hex("Projects",                      "RAHHHHHHHHHH", "Placeholder text two.", "#FFBE0B", "#FFFFFF", "#FEF08A", { x: 663,   y: 382 }),
    hex10: hex("Extracurricular",               "RAHHHHHHHHHH", "RAHHHHHHHHHH", "#7C3AED", "#FFFFFF", "#EDE9FE", { x: 265.5, y: 611 }),
    hex11: hex("Certifications", "Placeholder text one.", "Placeholder text two.", "#E63337", "#FFFFFF", "#FEE2E2", { x: 530.5, y: 611 }),

    "JE 1": hex("Resia IT Internship", "I was an IT intern for the Resia Company. I helped out greatly in IT operations aswell as gained core IT experience.", "I managed phone, laptop, electrical device inventory, aided in the ticket system, aswell as helped with computer or phone repairs", "#2ECC71", "#000000", "#A8F0C6", { x: 133,   y: -76  }),
    "JE 2": hex("Panera Bread Line Worker", "I was a line worker for the Panera Food Company.", "I prepared food accustomed to customer preference, maintained kitchen conditions healthy, and helped with customer inquiries.", "#ECD283", "#000000", "#F7EFC2", { x: 0,     y: -305 }),
    "Python Utility": hex("Python Utility", "Python Utility in projects such as: 'Lagotaxes' (Django Utility), and 'Soundmeet' (Django Utility).", "I love Python, and I'll probably be using it a ton in the future, for some planned projects involving API's.", "#3776AB", "#FFD43B", "#BDD8EE", { x: 663,   y: -76  }),
    "Java utility":   hex("Java Utility",   "Java Utility in projects such as: Calendar Program COP3370", "I love Java, mostly due to its simplicity and depth of knowledge. I've yet to use any pluggins like springboot yet, though.", "#E76F00", "#FFFFFF", "#F5CBA7", { x: 796,   y: -305 }),
    "Coral Reef Senior High": hex("Coral Reef Senior High", "Studied in Coral Reef Senior High under the IB Diploma before relocating.", "Made good memories in coral reef. I liked the campus alot actually", "#FF7F50", "#FFFFFF", "#FFD4C0", { x: -132,  y: 382  }),
    "Cambridge": hex("Cambridge", "Studied and graduated in Cambridge Senior High school, under the AICE diploma. Got bright futures", "Miss this school alot. but I'm having more fun in FIU, so there's always that.", "#A3C1AD", "#000000", "#D8EDE0", { x: -397,  y: 382  }),
    "FCC JS Projects": hex("FCC JS Projects", "I'm going to number here some of the projects I did under FCC. they were nice to do, and gave me some good JSX experience.", "FCC spotify, calorie tracker, project 1 - 5, RPG game-maker, etc.", "#006400", "#FFFFFF", "#A7F3D0", { x: 928,   y: 382  }),
    "SoundMeet":       { ...hex("Soundmeet", "I was a webpage designer aswell as a debugger for the project 'Soundmeet', A social media app for musicians.", "Here's the link for the app!", "#DC2E73", "#FFFFFF", "#F9B8D3", { x: 1193,  y: 382  }), link: "https://www.soundmeet.app/" },
    "LameTaxing":       hex("LameTaxing",        "I made a webpage for a company called 'LameTaxing'. It was fun! I generally enjoyed the design process for the webpage. ", "Here's the link for the project!", "#89BBC9", "#000000", "#D4EBF2", { x: 1325.5, y: 611  }),
    "Personal Website":hex("Personal Website", "I'm referring to this website! I loved making this website, even the tedious logic behind it was nice to make. It was an amazing experience that taught me alot, especially about rendering.", "I don't feel like I need to give you a link for this haha, but do tell me what you feel about this website in my socials. I love hearing feedback, truthfully.", "#8EC092", "#000000", "#D1EDD3", { x: 1325.5, y: 1069 }),
    "Envision":        hex("Envision",         "WIP website for the Envision Company.", "WIP", "#C45B2A", "#FFFFFF", "#F5D0B8", { x: 1060.5, y: 611  }),
    "Tookee":          hex("Tookee",           "WIP website for the Tookee Idea.", "WIP", "#242424", "#FFFFFF", "#C8C8C8", { x: 1193,   y: 840  }),
    "Django":     hex("Django Beginner", "Django utility in projects such as: 'Lagotaxes', and 'Soundmeet'. ", "Although Django does have many security benefits and ease of writing, I don't want to use it for my next projects. Lack of interest, honestly.", "#092E20", "#FFFFFF", "#A7F3D0", { x: 530,    y: -305 }),
    "Rust":       hex("Rust Beginner",  "I'm still learning Rust, Hahaha. I never used it though.", "I know, I know, it's an increadible new gen language that's super fast, secure, fixes bugs and can help you ascend your skills. I just want the basics first, though.", "#CE422B", "#FFFFFF", "#FECACA", { x: 1325.5, y: 153   }),
    "JavaScript": hex("JavaScript", "Avid JS coder. Utilized it through different libraries (React / Next JS) to build projects, such as LameTaxing, Soundmeet, or this website.", "I love JS, it's the first language that I've really learnt. I studied it in FCC, applied HTML and CSS, and then dropped it when I learnt that React was a thing.", "#F7DF1E", "#000000", "#FDF9C4", { x: 1325,   y: -305 }),
    "CSS":        hex("CSS",        "Applied CSS in: 'Soundmeet', 'LameTaxing'. ", "CSS was nice, but I preffer tailwind classes at this point. I still use css in index for keyframes of animation, but not as much anymore.", "#264DE4", "#FFFFFF", "#BCC8F7", { x: 1060.5, y: -305 }),
    "HTML":       hex("HTML",       "Applied HTML in: 'Soundmeet', 'LameTaxing'. ", "I liked using HTML, and I still use it for design. It's generally very nice and easy to use", "#E34F26", "#FFFFFF", "#F5C6B8", { x: 928,    y: -76  }),
    "React":      hex("React",      "This whole website is made in React! Also, 'lameTaxing' and 'Soundmeet' were also made using React.", "Avid React user. I program new projects with React + Tailwind 24/7. I'm trying to expand to use different languages though.", "#61DAFB", "#20232A", "#C8F4FD", { x: 1193,   y: -76  }),
    "Tailwind":   hex("Tailwind",   "Applied Tailwind throughout this whole website, and also in LameTaxing, Soundmeet.", "Tailwind is such a nice time saver, and I love using it for general design. ", "#0EA5E9", "#FFFFFF", "#BAE6FD", { x: 1060.5, y: 153  }),
    "JE 3": hex("FIU Sound IT Student Assistant", "I am a sound IT student assistant at FIU", "I mostly work with replacing Cisco Phones, upgrading devices and doing other cool stuff", "#081E3F", "#B6862C", "#C5D5E8", { x: 265,   y: -305 }),
    "JE 4": hex("(TO BE DISCLOSED)", "I don't know if I'm gonna get this job HAHAHA, but if I do, I'll change this hex for it.", "It's gonna be cool, I promise!", "#D0DCD3", "#000000", "#EEFBEF", { x: -265,  y: -305 }),
    "Routine Exercise": hex("Routine Exercise", "I do alot of exercise, I run around 4 / 5 miles per day and mostly work with calisthenics", "I'm not the biggest gym pro, but I do try my best", "#2f6a87", "#FFFFFF", "#B8D8E8", { x: 133,   y: 840  }),
    "LeetCode Practice": hex("LeetCode Practice", "I commonly do alot of leetcode practice in my normal study sessions. I'd like to put a live counter here of how many questions I've solved, but that's for another day", "Python never has really been my strong suit, but I just have to roll with it", "#2EC866", "#000000", "#AAFED0", { x: 0,     y: 1069 }),
    "Music": hex("Music", "Currently trying to learn piano. It's hard, but I enjoy my time playing it", "I'm also pretty decent in trumpet, baritone, and Tuba.", "#6B21A8", "#FFFFFF", "#E9D5FF", { x: -132.5, y: 840  }),
    "Arts":  hex("Arts",  "Currently learning how to draw again, and it's turning out decent", "Here's two of my most recent drawings: ", "#B45309", "#FFFFFF", "#FDE68A", { x: 265,    y: 1069 }),
    "Resia IT Internship": hex("Resia IT Cert",        "Here's my certification for the Resia IT Internship I undertook in 2024: ", "", "#4F4F4F", "#FFFFFF", "#CCCCCC", { x: 663,   y: 840  }),
    "FCC JS Certification": hex("FCC JS Certification", "Here's my certification for the JS Course I took in FreeCodeCamp back in 2025: ", "I'll get back to doing this, eventually.", "#F7DF1E", "#000000", "#FDF9C4", { x: 796,   y: 1069 }),
    "Paralegal Translator": hex("Paralegal Associate Form Translator", "I was a paralegal assistant translator for the company 'ParaLegal Services at Home LLC'.", "I constantly did translations for customers, aswell as readouts of immigrant services.", "#2C3E6B", "#FFFFFF", "#C8D0E8", { x: -132,  y: -76  }),
    "Codecademy":           hex("Codecademy Data Structures w/Python", "I got certified with the JavaScript Legacy course in FCC", "I made many projects out of JS, and enjoyed the learning curse there.", "#1F4056", "#FFFFFF", "#C0D8E8", { x: 531,   y: 1069 }),
    "AWS Foundations Certification": hex("AWS Foundations Certification", "Here are my certifications for the AWS Foundations:", "", "#FF9900", "#000000", "#FFEACC", { x: 928,   y: 840  }),
    "AWS AI Foundations Certification": hex("AWS AI Foundations Certification", "This is a WIP. Im currently trying to get certified for this", "", "#FF9970", "#000000", "#FFE8DE", { x: 1061,  y: 1069 }),
    "FIU":  hex("Florida International University", "I'm currently a student studying for a CSBS degree at FIU. Might transfer to a different university, who knows. I do love it here though", "Wish there were more CS students with passion for website-building, though.", "#003087", "#FFFFFF", "#C5D5E8", { x: -264.5, y: 611  }),
    "FCC":  hex("FCC", "I learnt alot with freecodecamp, specifically JSX", "I marked it here because it was, really, my first step into coding. I'd love to take their python face-scan course!", "#006400", "#FFFFFF", "#A7F3D0", { x: -264.5, y: 153  }),
}

const categoryChildren = {
    "Job Experience":      ["JE 1", "JE 2", "JE 3", "JE 4", "Paralegal Translator"],
    "Coding Experience":   ["Python Utility", "Java utility", "Django", "Rust", "JavaScript", "CSS", "HTML", "React", "Tailwind"],
    "Education":           ["Coral Reef Senior High", "Cambridge", "FIU", "FCC"],
    "Projects":            ["FCC JS Projects", "SoundMeet", "LameTaxing", "Personal Website", "Envision", "Tookee"],
    "Extracurricular":     ["Routine Exercise", "LeetCode Practice", "Music", "Arts"],
    "Certifications":      ["Resia IT Internship", "FCC JS Certification", "AWS Foundations Certification", "AWS AI Foundations Certification", "Codecademy"],
}

const hexPositions = Object.values(hexData).map(h => h.pos)
//Value declarations for stuff like x origins, hover animations, hooks to set the expanded hex state, stuff like that. Also the background scale. 
function HexagonSquaresPage() {
    const x = useMotionValue(0)
    const y = useMotionValue(0)
    const [activeHex, setActiveHex] = useState(null)
    const [selectedHex, setSelectedHex] = useState(null)
    const [expandedHexLabels, setExpandedHexLabels] = useState([])
    const [rainbowOrder, setRainbowOrder] = useState([0, 1, 2, 3, 4, 5])
    const [ripples, setRipples] = useState([])
    const [visitedHexes, setVisitedHexes] = useState(new Set())
    const [clickWave, setClickWave] = useState(null)
    const [floatingHex, setFloatingHex] = useState(null)
    const scale = useMotionValue(1)
    const autoZoom = useRef({ scale: 1, x: 0, y: 0 })
    useEffect(() => {
        const interval = setInterval(() => {
            const visibleKeys = expandedHexLabels.flatMap(label => categoryChildren[label] || [])
            if (visibleKeys.length === 0) return
            const key = visibleKeys[Math.floor(Math.random() * visibleKeys.length)]
            setFloatingHex(hexData[key])
            setTimeout(() => setFloatingHex(null), 3800)
        }, 5000)
        return () => clearInterval(interval)
    }, [expandedHexLabels])

    const spawnRipple = useCallback((left, top, color) => {
        const id = Date.now() + Math.random()
        setRipples(prev => [...prev, { id, left, top, color }])
        setTimeout(() => setRipples(prev => prev.filter(r => r.id !== id)), 800)
    }, [])

    //Don't forget this is LEGIT the background. 
    const handleChildClick = useCallback((data) => {
        playSFX('select')
        const isFirstClick = !visitedHexes.has(data.label)
        setVisitedHexes(prev => new Set([...prev, data.label]))
        spawnRipple(data.pos.x - 133, data.pos.y - 153, data.color)
        setSelectedHex(data)
        const zoomScale = Math.min(autoZoom.current.scale * 1.6, 1.4)
        animate(scale, zoomScale, { duration: 0.4 })
        animate(x, -zoomScale * (data.pos.x - 398), { duration: 0.4 })
        animate(y, -zoomScale * (data.pos.y - 392), { duration: 0.4 })
        setTimeout(() => {
            setActiveHex(data)
            if (isFirstClick) setClickWave({ id: Date.now() + Math.random(), pos: data.pos, color: data.color })
        }, 400)
    }, [visitedHexes, spawnRipple])

    const isRainbow = expandedHexLabels.length === 6

    useEffect(() => {
        if (isRainbow) {
            setRainbowOrder([0, 1, 2, 3, 4, 5].sort(() => Math.random() - 0.5))
        }
    }, [isRainbow])

    const handleTransitionClick = useCallback((data) => {
        playSFX('click')
        const isExpanding = !expandedHexLabels.includes(data.label)
        playSFX(isExpanding ? 'expand' : 'collapse')
        const newLabels = isExpanding
            ? [...expandedHexLabels, data.label]
            : expandedHexLabels.filter(l => l !== data.label)

        setExpandedHexLabels(newLabels)

        if (newLabels.length === 0) {
            autoZoom.current = { scale: 1, x: 0, y: 0 }
            animate(scale, 1, { duration: 0.5 })
            animate(x, 0, { duration: 0.5 })
            animate(y, 0, { duration: 0.5 })
            return
        }

        const parentKeys = ['hex2', 'hex3', 'hex4', 'hex5', 'hex6', 'hex10', 'hex11']
        const childKeys  = newLabels.flatMap(label => categoryChildren[label] || [])
        const positions  = [...parentKeys, ...childKeys].map(k => hexData[k].pos)
        //super important formula
        const minX = Math.min(...positions.map(p => p.x - 133))
        const maxX = Math.max(...positions.map(p => p.x + 133))
        const minY = Math.min(...positions.map(p => p.y - 153))
        const maxY = Math.max(...positions.map(p => p.y + 153))

        const bboxCx = (minX + maxX) / 2
        const bboxCy = (minY + maxY) / 2

        const requiredScale = Math.min(1, (window.innerWidth  * 0.85) / (maxX - minX),
                                          (window.innerHeight * 0.85) / (maxY - minY))

        const tx = -requiredScale * (bboxCx - 398)
        const ty = -requiredScale * (bboxCy - 392)
        autoZoom.current = { scale: requiredScale, x: tx, y: ty }

        // canvas div center is (398, 392), thus we just pan so that the bbox center lands at viewport center
        animate(scale, requiredScale, { duration: 0.5 })
        animate(x, tx, { duration: 0.5 })
        animate(y, ty, { duration: 0.5 })
    }, [expandedHexLabels])

    const activeBgHexes = expandedHexLabels
        .slice(-3)
        .map(label => Object.values(hexData).find(h => h.label === label))
        .filter(Boolean)

    const bgHexes = useMemo(() => isRainbow
        ? [hexData.hex2, hexData.hex3, hexData.hex4, hexData.hex6, hexData.hex10, hexData.hex11]
            .map((h, i) => ({ ...h, lightColor: RB_LIGHT[rainbowOrder[i]] }))
        : activeBgHexes
    , [isRainbow, rainbowOrder, activeBgHexes])

    return (
        <div className="fixed inset-0 overflow-hidden cursor-grab active:cursor-grabbing" style={{ perspective: '2000px' }}>
            <motion.div
                drag
                style={{ x, y, scale }}
                dragConstraints={{ left: -500, right: 500, top: -400, bottom: 400 }}
                dragTransition={{ power: 0.3, timeConstant: 400 }}
                className="flex items-center justify-center w-screen h-screen relative z-1"
            >
                <HexBackground selectedHexes={bgHexes} expandedHexLabels={expandedHexLabels} hexPositions={hexPositions} panX={x} panY={y} panScale={scale} clickWave={clickWave} isRainbow={isRainbow} />

                {/* THE OG GRIID, Gabriel Lago at center, 6 transition hexes <-- You're about to see the wall of divs. Buckle up. */}
                <div className="relative w-[796px] h-[784px]">


                    <AnimatePresence>
                        {expandedHexLabels.includes("Job Experience") && (
                            <Fragment key="je">
                                <BorderChase left="0px" top="-229px" color={hexData["JE 1"].color} />
                                {/* Row -458: JE 4, JE 2, JE 3, JE 5 */}
                                <div style={{ position: 'absolute', left: '-397.5px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["JE 4"].color} borderColor="#9AAAA3" glowColor={hexData["JE 4"].color} label={hexData["JE 4"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["JE 4"]} selected={selectedHex === hexData["JE 4"]} floating={floatingHex === hexData["JE 4"]} wip />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '-132.5px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["JE 2"].color} borderColor="#B09040" glowColor={hexData["JE 2"].color} label={hexData["JE 2"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["JE 2"]} selected={selectedHex === hexData["JE 2"]} floating={floatingHex === hexData["JE 2"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '132px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["JE 3"].color} borderColor="#132E5F" glowColor={hexData["JE 3"].color} label={hexData["JE 3"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["JE 3"]} selected={selectedHex === hexData["JE 3"]} floating={floatingHex === hexData["JE 3"]} />
                                    </motion.div>
                                </div>
                                {/* Row -229: JE 1, Paralegal <--- I made AI do some of the hexes, so some comments just stick around like this one*/}
                                <div style={{ position: 'absolute', left: '0px', top: '-229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0 }}>
                                        <Hexagon color={hexData["JE 1"].color} borderColor="#1A8C4E" glowColor={hexData["JE 1"].color} label={hexData["JE 1"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["JE 1"]} selected={selectedHex === hexData["JE 1"]} floating={floatingHex === hexData["JE 1"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '-265px', top: '-229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["Paralegal Translator"].color} borderColor="#1A2848" glowColor={hexData["Paralegal Translator"].color} label={hexData["Paralegal Translator"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Paralegal Translator"]} selected={selectedHex === hexData["Paralegal Translator"]} floating={floatingHex === hexData["Paralegal Translator"]} />
                                    </motion.div>
                                </div>
                            </Fragment>
                        )}
                        {expandedHexLabels.includes("Coding Experience") && (
                            <Fragment key="ce">
                                <BorderChase left="1060px" top="-229px" color={hexData["React"].color} />
                                <div style={{ position: 'absolute', left: '662.5px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["Java utility"].color} borderColor="#B85A00" glowColor={hexData["Java utility"].color} label={hexData["Java utility"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Java utility"]} selected={selectedHex === hexData["Java utility"]} floating={floatingHex === hexData["Java utility"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '397.5px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["Django"].color} borderColor="#071A14" glowColor={hexData["Django"].color} label={hexData["Django"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Django"]} selected={selectedHex === hexData["Django"]} floating={floatingHex === hexData["Django"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '530px', top: '-229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 2.25 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0 }}>
                                        <Hexagon color={hexData["Python Utility"].color} borderColor="#2B5B84" glowColor={hexData["Python Utility"].color} label={hexData["Python Utility"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Python Utility"]} selected={selectedHex === hexData["Python Utility"]} floating={floatingHex === hexData["Python Utility"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '1192.5px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["JavaScript"].color} borderColor="#C9B500" glowColor={hexData["JavaScript"].color} label={hexData["JavaScript"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["JavaScript"]} selected={selectedHex === hexData["JavaScript"]} floating={floatingHex === hexData["JavaScript"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '927.5px', top: '-458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["CSS"].color} borderColor="#1A35A0" glowColor={hexData["CSS"].color} label={hexData["CSS"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["CSS"]} selected={selectedHex === hexData["CSS"]} floating={floatingHex === hexData["CSS"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '795px', top: '-229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0.75 }}>
                                        <Hexagon color={hexData["HTML"].color} borderColor="#B33D1C" glowColor={hexData["HTML"].color} label={hexData["HTML"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["HTML"]} selected={selectedHex === hexData["HTML"]} floating={floatingHex === hexData["HTML"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '1060px', top: '-229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 2.25 }}>
                                        <Hexagon color={hexData["React"].color} borderColor="#2BB5D8" glowColor={hexData["React"].color} label={hexData["React"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["React"]} selected={selectedHex === hexData["React"]} floating={floatingHex === hexData["React"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '927.5px', top: '0px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 2.25 }}>
                                        <Hexagon color={hexData["Tailwind"].color} borderColor="#0284C7" glowColor={hexData["Tailwind"].color} label={hexData["Tailwind"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Tailwind"]} selected={selectedHex === hexData["Tailwind"]} floating={floatingHex === hexData["Tailwind"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '1192.5px', top: '0px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 2.25 }}>
                                        <Hexagon color={hexData["Rust"].color} borderColor="#A33218" glowColor={hexData["Rust"].color} label={hexData["Rust"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Rust"]} selected={selectedHex === hexData["Rust"]} floating={floatingHex === hexData["Rust"]} />
                                    </motion.div>
                                </div>
                            </Fragment>
                        )}
                        {expandedHexLabels.includes("Education") && (
                            <Fragment key="ed">
                                <div style={{ position: 'absolute', left: '-397.5px', top: '0px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["FCC"].color} borderColor="#004D00" glowColor={hexData["FCC"].color} label={hexData["FCC"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["FCC"]} selected={selectedHex === hexData["FCC"]} floating={floatingHex === hexData["FCC"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '-530px', top: '229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["Cambridge"].color} borderColor="#6B9077" glowColor={hexData["Cambridge"].color} label={hexData["Cambridge"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Cambridge"]} selected={selectedHex === hexData["Cambridge"]} floating={floatingHex === hexData["Cambridge"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '-265px', top: '229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0 }}>
                                        <Hexagon color={hexData["Coral Reef Senior High"].color} borderColor="#CC4D20" glowColor={hexData["Coral Reef Senior High"].color} label={hexData["Coral Reef Senior High"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Coral Reef Senior High"]} selected={selectedHex === hexData["Coral Reef Senior High"]} floating={floatingHex === hexData["Coral Reef Senior High"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '-397.5px', top: '458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["FIU"].color} borderColor="#002266" glowColor={hexData["FIU"].color} label={hexData["FIU"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["FIU"]} selected={selectedHex === hexData["FIU"]} floating={floatingHex === hexData["FIU"]} />
                                    </motion.div>
                                </div>
                            </Fragment>
                        )}
                        {expandedHexLabels.includes("Projects") && (
                            <Fragment key="pr">
                                <BorderChase left="1060px" top="229px" color={hexData["SoundMeet"].color} />
                                <div style={{ position: 'absolute', left: '1060px', top: '229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["SoundMeet"].color} borderColor="#A01F55" glowColor={hexData["SoundMeet"].color} label={hexData["SoundMeet"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["SoundMeet"]} selected={selectedHex === hexData["SoundMeet"]} floating={floatingHex === hexData["SoundMeet"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '795px', top: '229px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 2.25 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0 }}>
                                        <Hexagon color={hexData["FCC JS Projects"].color} borderColor="#004D00" glowColor={hexData["FCC JS Projects"].color} label={hexData["FCC JS Projects"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["FCC JS Projects"]} selected={selectedHex === hexData["FCC JS Projects"]} floating={floatingHex === hexData["FCC JS Projects"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '1192.5px', top: '458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["LameTaxing"].color} borderColor="#6B97A8" glowColor={hexData["LameTaxing"].color} label={hexData["LameTaxing"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["LameTaxing"]} selected={selectedHex === hexData["LameTaxing"]} floating={floatingHex === hexData["LameTaxing"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '927.5px', top: '458px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["Envision"].color} borderColor="#8B3D1A" glowColor={hexData["Envision"].color} label={hexData["Envision"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Envision"]} selected={selectedHex === hexData["Envision"]} floating={floatingHex === hexData["Envision"]} wip/>
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '1060px', top: '687px', zIndex: 2 }}>
                                    <motion.div initial={{ x: 265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 2.25 }}>
                                        <Hexagon color={hexData["Tookee"].color} borderColor="#484848" glowColor={hexData["Tookee"].color} label={hexData["Tookee"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Tookee"]} selected={selectedHex === hexData["Tookee"]} floating={floatingHex === hexData["Tookee"]} wip />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '1192.5px', top: '916px', zIndex: 2 }}>
                                    <motion.div initial={{ x: -132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 2.25 }}>
                                        <Hexagon color={hexData["Personal Website"].color} borderColor="#6FA074" glowColor={hexData["Personal Website"].color} label={hexData["Personal Website"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Personal Website"]} selected={selectedHex === hexData["Personal Website"]} floating={floatingHex === hexData["Personal Website"]} />
                                    </motion.div>
                                </div>
                            </Fragment>
                        )}
                        {expandedHexLabels.includes("Extracurricular") && (
                            <Fragment key="ec">
                                <div style={{ position: 'absolute', left: '-265.5px', top: '687px', zIndex: 3 }}>
                                    <motion.div initial={{ x: 132.5, y: 229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: 229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["Music"].color} borderColor="#4B1280" glowColor={hexData["Music"].color} label={hexData["Music"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Music"]} selected={selectedHex === hexData["Music"]} floating={floatingHex === hexData["Music"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '0px', top: '687px', zIndex: 3 }}>
                                    <motion.div initial={{ x: 132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0 }}>
                                        <Hexagon color={hexData["Routine Exercise"].color} borderColor="#1C4A62" glowColor={hexData["Routine Exercise"].color} label={hexData["Routine Exercise"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Routine Exercise"]} selected={selectedHex === hexData["Routine Exercise"]} floating={floatingHex === hexData["Routine Exercise"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '-132.5px', top: '916px', zIndex: 3 }}>
                                    <motion.div initial={{ x: 132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["LeetCode Practice"].color} borderColor="#1A8C44" glowColor={hexData["LeetCode Practice"].color} label={hexData["LeetCode Practice"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["LeetCode Practice"]} selected={selectedHex === hexData["LeetCode Practice"]} floating={floatingHex === hexData["LeetCode Practice"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '132px', top: '916px', zIndex: 3 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["Arts"].color} borderColor="#8B3D00" glowColor={hexData["Arts"].color} label={hexData["Arts"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Arts"]} selected={selectedHex === hexData["Arts"]} floating={floatingHex === hexData["Arts"]} />
                                    </motion.div>
                                </div>
                            </Fragment>
                        )}
                        {expandedHexLabels.includes("Certifications") && (
                            <Fragment key="hl">
                                <div style={{ position: 'absolute', left: '530px', top: '687px', zIndex: 3 }}>
                                    <motion.div initial={{ x: -132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 2.25 } }} transition={{ duration: 0.75, ease: 'ease-in-out', delay: 0 }}>
                                        <Hexagon color={hexData["Resia IT Internship"].color} borderColor="#2E2E2E" glowColor={hexData["Resia IT Internship"].color} label={hexData["Resia IT Internship"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Resia IT Internship"]} selected={selectedHex === hexData["Resia IT Internship"]} floating={floatingHex === hexData["Resia IT Internship"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '795px', top: '687px', zIndex: 3 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0.75 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 1.5 }}>
                                        <Hexagon color={hexData["AWS Foundations Certification"].color} borderColor="#CC7A00" glowColor={hexData["AWS Foundations Certification"].color} label={hexData["AWS Foundations Certification"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["AWS Foundations Certification"]} selected={selectedHex === hexData["AWS Foundations Certification"]} floating={floatingHex === hexData["AWS Foundations Certification"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '398px', top: '916px', zIndex: 3 }}>
                                    <motion.div initial={{ x: 132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: 132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["Codecademy"].color} borderColor="#122638" glowColor={hexData["Codecademy"].color} label={hexData["Codecademy"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["Codecademy"]} selected={selectedHex === hexData["Codecademy"]} floating={floatingHex === hexData["Codecademy"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '662.5px', top: '916px', zIndex: 3 }}>
                                    <motion.div initial={{ x: -132.5, y: -229, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -132.5, y: -229, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 1.5 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 0.75 }}>
                                        <Hexagon color={hexData["FCC JS Certification"].color} borderColor="#C9B500" glowColor={hexData["FCC JS Certification"].color} label={hexData["FCC JS Certification"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["FCC JS Certification"]} selected={selectedHex === hexData["FCC JS Certification"]} floating={floatingHex === hexData["FCC JS Certification"]} />
                                    </motion.div>
                                </div>
                                <div style={{ position: 'absolute', left: '928px', top: '916px', zIndex: 3 }}>
                                    <motion.div initial={{ x: -265, y: 0, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={{ x: -265, y: 0, opacity: 0, transition: { duration: 0.75, ease: 'easeIn', delay: 0 } }} transition={{ duration: 0.75, ease: 'ease-in', delay: 2.25 }}>
                                        <Hexagon color={hexData["AWS AI Foundations Certification"].color} borderColor="#CC6644" glowColor={hexData["AWS AI Foundations Certification"].color} label={hexData["AWS AI Foundations Certification"].label} onClick={handleChildClick} visitedSet={visitedHexes} data={hexData["AWS AI Foundations Certification"]} selected={selectedHex === hexData["AWS AI Foundations Certification"]} floating={floatingHex === hexData["AWS AI Foundations Certification"]} />
                                    </motion.div>
                                </div>
                            </Fragment>
                        )}
                    </AnimatePresence>

                    {/* Grid-level ripples — above all hex stacking contexts */}
                    {ripples.map(r => (
                        <motion.svg
                            key={r.id}
                            viewBox="0 0 266 306"
                            style={{ position: 'absolute', left: r.left, top: r.top, width: '266px', height: '306px', zIndex: 10, pointerEvents: 'none', overflow: 'visible' }}
                            initial={{ scale: 1, opacity: 1 }}
                            animate={{ scale: 2, opacity: 0 }}
                            transition={{ duration: 1, ease: 'easeOut' }}
                        >
                            <polygon
                                points="133,0 266,76.5 266,229.5 133,306 0,229.5 0,76.5"
                                fill="none"
                                stroke={r.color}
                                strokeWidth="8"
                            />
                        </motion.svg>
                    ))}
                    {/* When I first started this, I made the AI do some of the hexes with the diamond shape in mind. THIS IS THE OG DIAMONDS, it has the ternary rainbowOrder and everything.*/}
                    {/* Row 1 — upper two */}
                    <div style={{ position: 'absolute', left: '132.5px', top: '0px', zIndex: 2 }}>
                        <Hexagon color={isRainbow ? RB_COLORS[rainbowOrder[0]] : hexData.hex2.color} borderColor={isRainbow ? RB_BORDERS[rainbowOrder[0]] : "#B45309"} glowColor={isRainbow ? RB_COLORS[rainbowOrder[0]] : "#FBB24A"} label={hexData.hex2.label} onClick={handleTransitionClick} data={hexData.hex2} important={expandedHexLabels.includes(hexData.hex2.label)} />
                    </div>
                    <div style={{ position: 'absolute', left: '397.5px', top: '0px', zIndex: 2 }}>
                        <Hexagon color={isRainbow ? RB_COLORS[rainbowOrder[1]] : hexData.hex3.color} borderColor={isRainbow ? RB_BORDERS[rainbowOrder[1]] : "#374151"} glowColor={isRainbow ? RB_COLORS[rainbowOrder[1]] : "#FFFFFF"} label={hexData.hex3.label} onClick={handleTransitionClick} data={hexData.hex3} important={expandedHexLabels.includes(hexData.hex3.label)} />
                    </div>

                    {/* Row 2 — center row */}
                    <div style={{ position: 'absolute', left: '0px', top: '229px', zIndex: 2 }}>
                        <Hexagon color={isRainbow ? RB_COLORS[rainbowOrder[2]] : hexData.hex4.color} borderColor={isRainbow ? RB_BORDERS[rainbowOrder[2]] : "#1E3A8A"} glowColor={isRainbow ? RB_COLORS[rainbowOrder[2]] : "#3B82F6"} label={hexData.hex4.label} onClick={handleTransitionClick} data={hexData.hex4} important={expandedHexLabels.includes(hexData.hex4.label)} />
                    </div>
                    <div style={{ position: 'absolute', left: '265px', top: '229px', zIndex: 2 }}>
                        <Hexagon color={hexData.hex5.color} borderColor="#D0D0D0" glowColor="#FFFFFF" label={hexData.hex5.label} onClick={setActiveHex} data={hexData.hex5} />
                    </div>
                    <div style={{ position: 'absolute', left: '530px', top: '229px', zIndex: 2 }}>
                        <Hexagon color={isRainbow ? RB_COLORS[rainbowOrder[3]] : hexData.hex6.color} borderColor={isRainbow ? RB_BORDERS[rainbowOrder[3]] : "#92400E"} glowColor={isRainbow ? RB_COLORS[rainbowOrder[3]] : "#FCD34D"} label={hexData.hex6.label} onClick={handleTransitionClick} data={hexData.hex6} important={expandedHexLabels.includes(hexData.hex6.label)} />
                    </div>

                    {/* Row 3 — lower two */}
                    <div style={{ position: 'absolute', left: '132.5px', top: '458px', zIndex: 2 }}>
                        <Hexagon color={isRainbow ? RB_COLORS[rainbowOrder[4]] : hexData.hex10.color} borderColor={isRainbow ? RB_BORDERS[rainbowOrder[4]] : "#5B21B6"} glowColor={isRainbow ? RB_COLORS[rainbowOrder[4]] : "#A78BFA"} label={hexData.hex10.label} onClick={handleTransitionClick} data={hexData.hex10} important={expandedHexLabels.includes(hexData.hex10.label)} />
                    </div>
                    <div style={{ position: 'absolute', left: '397.5px', top: '458px', zIndex: 2 }}>
                        <Hexagon color={isRainbow ? RB_COLORS[rainbowOrder[5]] : hexData.hex11.color} borderColor={isRainbow ? RB_BORDERS[rainbowOrder[5]] : "#A01F22"} glowColor={isRainbow ? RB_COLORS[rainbowOrder[5]] : "#E63337"} label={hexData.hex11.label} onClick={handleTransitionClick} data={hexData.hex11} important={expandedHexLabels.includes(hexData.hex11.label)} />
                    </div>

                </div>
            </motion.div>

            {/* Panelling segment */}
            <AnimatePresence>
                {activeHex && (
                    <>
                        <div
                            className="fixed inset-0 z-10"
                            onClick={() => {
                                playSFX('panelClose')
                                animate(scale, autoZoom.current.scale, { duration: 0.4 })
                                animate(x, autoZoom.current.x, { duration: 0.4 })
                                animate(y, autoZoom.current.y, { duration: 0.4 })
                                setTimeout(() => setActiveHex(null), 400)
                                setTimeout(() => setSelectedHex(null), 800)
                            }}
                        />
                        <motion.div
                            className="fixed right-0 top-0 h-full z-20 flex flex-row gap-0.5"
                            initial={{ x: '100%', opacity: 0 }}
                            animate={{ x: 0, opacity: 1 }}
                            exit={{ x: '100%', opacity: 0 }}
                            transition={{ duration: 0.4, ease: 'easeInOut' }}
                        >
                            <div className="h-full" style={{ width: '0.42vw', backgroundColor: activeHex.color, opacity: 0.7 }} />
                            <div className="h-full" style={{ width: '0.83vw', backgroundColor: activeHex.color, opacity: 0.8 }} />
                            <div
                                className="h-full flex flex-col"
                                style={{ width: '31.8vw', padding: '2.5vw', gap: '1.7vw', backgroundColor: activeHex.color + 'E6' }}
                            >
                                <h1 className="font-['Inria_Serif'] italic font-bold text-center" style={{ color: activeHex.textColor, fontSize: '1.875vw' }}>{activeHex.label}</h1>
                                <hr style={{ borderColor: activeHex.textColor, opacity: 0.4 }} />
                                <p className="font-['Inria_Serif'] italic text-center" style={{ color: activeHex.textColor, fontSize: '1.25vw' }}>{activeHex.para1}</p>
                                <p className="font-['Inria_Serif'] italic text-center" style={{ color: activeHex.textColor, fontSize: '1.25vw' }}>{activeHex.para2}</p>
                                {activeHex.link && (
                                    <a
                                        href={activeHex.link}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="font-['Inria_Serif'] italic font-bold text-center underline"
                                        style={{ color: activeHex.textColor, fontSize: '1.1vw', opacity: 0.85 }}
                                        onClick={e => e.stopPropagation()}
                                    >
                                        Visit →
                                    </a>
                                )}
                                <div className="flex flex-row mt-30 items-center justify-center" style={{ gap: '2.5vw' }}>
                                    <div className="bg-white rounded-2xl opacity-60 border-4 " style={{ width: '12.5vw', height: '30vh', borderColor: 'black' }} />
                                    <div className="bg-white rounded-2xl opacity-60 border-4 " style={{ width: '12.5vw', height: '30vh', borderColor: 'black' }} />
                                    
                                </div>
                                <svg viewBox="0 0 400 60" preserveAspectRatio="none" style={{ width: '100%', height: '35%', position: 'absolute', bottom: 0, left: 0 }}>
                                    <path d="M0,30 C80,60 160,0 240,30 C320,60 370,10 400,30 L400,60 L0,60 Z" fill={activeHex.textColor} opacity={0.10} />
                                    <path d="M0,40 C100,10 200,60 300,30 C350,15 380,40 400,35 L400,60 L0,60 Z" fill={activeHex.textColor} opacity={0.06} />
                                </svg>
                            </div>
                        </motion.div>
                    </>
                )}
            </AnimatePresence>

        </div>
    )
}

export default HexagonSquaresPage
